### ISSUE TITLE
Example config does not match XSD

### ISSUE THREAD

**Issue by anton-johansson** [hazelcast/hazelcast-kubernetes#126]
Looking at [the XSD for Hazelcast](https://hazelcast.com/schema/config/hazelcast-config-3.10.xsd), it doesn't really match the example configuration:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://hazelcast.com/schema/config
           https://hazelcast.com/schema/config/hazelcast-config-3.10.xsd">
    <group>
        <name>hazelcast-tomcat-session</name>
        <password></password>
    </group>
    <network>
        <join>
            <multicast enabled="false"/>
            <kubernetes enabled="true">
                <namespace>${kubernetesNamespace}</namespace>
                <service-name>${kubernetesServiceName}</service-name>
            </kubernetes>
        </join>
    </network>
</hazelcast>
```

There's no such element `kubernetes` under `join`. I'm getting the following exception when starting Tomcat in my container (I'm not in Kubernetes yet, still raw Docker, but it shouldn't matter at this point):
```
14-Jan-2019 12:15:41.177 SEVERE [main] org.apache.catalina.startup.Catalina.start The required Server component failed to start so Tomcat is unable to start.
 org.apache.catalina.LifecycleException: Failed to start component [StandardServer[8005]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:641)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:349)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:483)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardService[Catalina]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:789)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 7 more
Caused by: com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'kubernetes'. One of '{"http://www.hazelcast.com/schema/config":tcp-ip, "http://www.hazelcast.com/schema/config":aws, "http://www.hazelcast.com/schema/config":discovery-strategies}' is expected.
        at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:189)
        at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:242)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:223)
        at com.hazelcast.config.UrlXmlConfig.<init>(UrlXmlConfig.java:94)
        at com.hazelcast.config.UrlXmlConfig.<init>(UrlXmlConfig.java:72)
        at com.hazelcast.config.ConfigLoader.load(ConfigLoader.java:41)
        at com.hazelcast.session.P2PLifecycleListener.lifecycleEvent(P2PLifecycleListener.java:29)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:388)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:333)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:436)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 9 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 40; cvc-complex-type.2.4.a: Invalid content was found starting with element 'kubernetes'. One of '{"http://www.hazelcast.com/schema/config":tcp-ip, "http://www.hazelcast.com/schema/config":aws, "http://www.hazelcast.com/schema/config":discovery-strategies}' is expected.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:453)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3231)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1791)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:741)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:568)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.validate(ValidatorHandlerImpl.java:726)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:102)
        at javax.xml.validation.Validator.validate(Validator.java:124)
        at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:187)
        ... 21 more
```

**Comment by mesutcelik** [comment]
Hi,
This new discovery tags has been introduced in 3.11 so can you try with the latest hazelcast version 3.11.1 ?

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-config-3.11.xsd#L1812

**Comment by anton-johansson** [comment]
Aha, I see. I will give it a try (altough that means Hazelcast `3.11-BETA` until a new version of this repository is released, if I've understood things correctly).

**Comment by mesutcelik** [comment]
Yes, you are right but you can override it in your pom.xml and use 3.11.1

**Comment by anton-johansson** [comment]
Allright, thanks!

**Comment by anton-johansson** [comment]
Hm, I'm getting the same error with this one too. I also cannot see the new `kubernetes` element in https://hazelcast.com/schema/config/hazelcast-config-3.11.xsd.

**Comment by mesutcelik** [comment]
Normally, schema validation is done against the XSDs embedded into hazelcast.jar. The one on the webserver is for references. 

Can you please make sure 3.11 is only on the classpath with no other hazelcast version?
Can you also define schema file by its name only?
`xsi:schemaLocation="https://hazelcast.com/schema/config hazelcast-config-3.11.xsd`

**Comment by anton-johansson** [comment]
Using the name only seems to have gotten me further. Thank you very much!

**Comment by ravindranathakila** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.11.xsd">
    <network>
        <join>
            <multicast enabled="false"/>
            <kubernetes enabled="true">
                <namespace>default</namespace>
                <service-name>hazelcast</service-name>
            </kubernetes>
        </join>
    </network>
</hazelcast>
```

and only worked with:

```

            <dependency>
                <groupId>com.hazelcast</groupId>
                <artifactId>hazelcast</artifactId>
                <version>3.11</version>
            </dependency>
            <dependency>
                <groupId>com.hazelcast</groupId>
                <artifactId>hazelcast-kubernetes</artifactId>
                <version>1.3.1</version>
            </dependency>
```
