### ISSUE TITLE
Two kubernetes clusters... is there any way to connect Hazelcast nodes?

### ISSUE THREAD

**Issue by hugree** [hazelcast/hazelcast-kubernetes#141]
We are using the hazelcast-kubernetes plugin for Kubernetes and it works fine.

Now since we want to build a Highly Available Kubernetes cluster and use two clusters for our services I'm wondering is there any way to form a Hazelcast cluster that's able to discover Hazlecast nodes (let's say within the same namespace) across both Kubernetes clusters???

**Comment by leszko** [comment]
@hugree Yes, it's possible. Let me mention the options you have:

1. Create one Kubernetes cluster which contains nodes in multiple zones (i.e. GKE supports it) and then use [Hazelcast ZONE_AWARE feature](https://github.com/hazelcast/hazelcast-kubernetes#zone-aware).

2. Exchange service account token and ca-certificate and use a configuration similar to the one mentioned for the [external client.](https://github.com/hazelcast/hazelcast-kubernetes#outside-kubernetes-cluster) (check also [External Client Code Sample](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes/samples/external-client); if your both k8 clusters share the same VPC, then you don't need to expose IPs with Metacontroller)

3. Use [Hazelcast WAN Replication](https://hazelcast.com/product-features/wan-replication/) (Enterprise Feature). Then, you'll have two separate Hazelcast clusters which share the data.

Hope it helps.

**Comment by hugree** [comment]
Option #2 sounds like something we can use. I will definitely check it out. Will it work with server nodes too or only clients? 

Thank you for a blazing fast response!

By the way... we're running on Azure AKS but we do use one Application Network (VPC).

**Comment by leszko** [comment]
It will work for server nodes too. If you use one Azure VPC, then you don't specify `<use-public-ip>true</use-public-ip>`, because one VPC means they use the private Kubernetes addresses.

The configuration for the Hazelcast member will be actually the same as for the Hazelcast Client, so I guess you'll sort it out. If you encounter any issues, let me know.

**Comment by hugree** [comment]
I've finally got around to try this out... I'm close, I think, but I'm missing something at the moment

I'm going for the smart client.

I was able to configure the second cluster to user the master node from the first cluster.

This is the endpoints list from Cluster #1 
```json
{
  "kind": "Endpoints",
  "apiVersion": "v1",
  "metadata": {
    "name": "cache-service",
    "namespace": "playground",
    "selfLink": "/api/v1/namespaces/playground/endpoints/cache-service",
    "uid": "d709e95c-6c38-11e9-ae3c-5212da82bec7",
    "resourceVersion": "343951",
    "creationTimestamp": "2019-05-01T17:44:59Z"
  },
  "subsets": [
    {
      "addresses": [
        {
          "ip": "10.1.16.92",
          "nodeName": "aks-default-36104175-2",
          "targetRef": {
            "kind": "Pod",
            "namespace": "playground",
            "name": "cache-service-0",
            "uid": "2eaf923b-6c41-11e9-ae3c-5212da82bec7",
            "resourceVersion": "343950"
          }
        }
      ],
      "ports": [
        {
          "name": "http",
          "port": 8080,
          "protocol": "TCP"
        },
        {
          "name": "hazelcast",
          "port": 5701,
          "protocol": "TCP"
        }
      ]
    }
  ]
}
```

and this is the service created by the Metacontroller

```json
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "cache-service-0",
    "namespace": "playground",
    "selfLink": "/api/v1/namespaces/playground/services/cache-service-0",
    "uid": "2ea61b7d-6c41-11e9-ae3c-5212da82bec7",
    "resourceVersion": "343773",
    "creationTimestamp": "2019-05-01T18:44:42Z",
    "labels": {
      "app": "service-per-pod"
    },
    "annotations": {
      "metacontroller.k8s.io/decorator-controller": "service-per-pod",
      "metacontroller.k8s.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"metacontroller.k8s.io/decorator-controller\":\"service-per-pod\"},\"labels\":{\"app\":\"service-per-pod\"},\"name\":\"cache-service-0\"},\"spec\":{\"ports\":[{\"port\":5701,\"targetPort\":5701}],\"selector\":{\"app-0\":\"cache-service-0\"}}}"
    },
    "ownerReferences": [
      {
        "apiVersion": "apps/v1beta1",
        "kind": "StatefulSet",
        "name": "cache-service",
        "uid": "2e97939f-6c41-11e9-ae3c-5212da82bec7",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "ports": [
      {
        "protocol": "TCP",
        "port": 5701,
        "targetPort": 5701
      }
    ],
    "selector": {
      "app-0": "cache-service-0"
    },
    "clusterIP": "10.0.167.114",
    "type": "ClusterIP",
    "sessionAffinity": "None"
  },
  "status": {
    "loadBalancer": {
      
    }
  }
}
```

However, when the Cluster #2 tries to form the cluster I get the following error:
```
2019-05-01 18:52:17.467 [                     main] [INFO ] [            c.h.s.d.integration.DiscoveryService] : [10.1.32.89]:5701 [dev] [3.12] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: cache-service, service-port: 0, service-label: null, service-label-value: true, namespace: playground, resolve-not-ready-addresses: false, kubernetes-api-retries: 3, kubernetes-master: https://playground-a1a288d5.hcp.westeurope.azmk8s.io} 
2019-05-01 18:52:17.471 [                     main] [INFO ] [            c.h.s.d.integration.DiscoveryService] : [10.1.32.89]:5701 [dev] [3.12] Kubernetes Discovery activated with mode: KUBERNETES_API 
2019-05-01 18:52:17.673 [                     main] [INFO ] [                     com.hazelcast.instance.Node] : [10.1.32.89]:5701 [dev] [3.12] Activating Discovery SPI Joiner 
2019-05-01 18:52:18.866 [                     main] [INFO ] [            c.h.s.i.o.impl.OperationExecutorImpl] : [10.1.32.89]:5701 [dev] [3.12] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks) 
2019-05-01 18:52:18.867 [                     main] [INFO ] [            c.h.internal.diagnostics.Diagnostics] : [10.1.32.89]:5701 [dev] [3.12] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments. 
2019-05-01 18:52:18.874 [                     main] [INFO ] [             com.hazelcast.core.LifecycleService] : [10.1.32.89]:5701 [dev] [3.12] [10.1.32.89]:5701 is STARTING 
2019-05-01 18:52:18.875 [                     main] [DEBUG] [        c.h.i.partition.InternalPartitionService] : [10.1.32.89]:5701 [dev] [3.12] Adding Member [10.1.32.89]:5701 - e7e4d500-b51d-4d91-9169-f813e33bd15d this 
2019-05-01 18:52:18.877 [                     main] [DEBUG] [              c.h.i.networking.nio.NioNetworking] : [10.1.32.89]:5701 [dev] [3.12] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads 
2019-05-01 18:52:18.877 [                     main] [DEBUG] [              c.h.i.networking.nio.NioNetworking] : [10.1.32.89]:5701 [dev] [3.12] IO threads selector mode is SELECT 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (jar:file:/cache-service/BOOT-INF/lib/hazelcast-3.12.jar!/) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-05-01 18:52:19.806 [                     main] [WARN ] [             com.hazelcast.kubernetes.RetryUtils] : Couldn't discover Hazelcast members using Kubernetes API, [1] retrying in 1 seconds... 
2019-05-01 18:52:21.379 [                     main] [WARN ] [             com.hazelcast.kubernetes.RetryUtils] : Couldn't discover Hazelcast members using Kubernetes API, [2] retrying in 2 seconds... 
2019-05-01 18:52:23.696 [                     main] [WARN ] [             com.hazelcast.kubernetes.RetryUtils] : Couldn't discover Hazelcast members using Kubernetes API, [3] retrying in 3 seconds... 
2019-05-01 18:52:27.174 [                     main] [WARN ] [            c.h.s.d.integration.DiscoveryService] : [10.1.32.89]:5701 [dev] [3.12] Cannot fetch the current zone, ZONE_AWARE feature is disabled 
2019-05-01 18:52:27.176 [                     main] [DEBUG] [             c.h.internal.cluster.ClusterService] : [10.1.32.89]:5701 [dev] [3.12] Setting master address to null 
2019-05-01 18:52:27.482 [                     main] [TRACE] [         c.hazelcast.kubernetes.KubernetesClient] : Cannot fetch nodeName from the following PODs: [10.1.16.92:null] 
com.hazelcast.kubernetes.KubernetesClientException: Cannot fetch nodeName from the following PODs: [10.1.16.92:null]
	at com.hazelcast.kubernetes.KubernetesClient.extractNodes(KubernetesClient.java:383)
	at com.hazelcast.kubernetes.KubernetesClient.enrichWithPublicAddresses(KubernetesClient.java:279)
```

As you can see Cluster #2 has read the IP, but I'm not sure that Service has been configured properly with that null in there. Also `Setting master address to null` has me worried as well.

Any tips would be appreciated. Thanks!

**Comment by hugree** [comment]
Another update. After finding in the sourcecode
```java
// Service must have one and only one Node Port assigned.
        if (ports.size() != 1) {
            throw new KubernetesClientException("Cannot fetch nodePort from the service");
        }
```
I removed one additional port and now I'm getting 
```
2019-05-01 20:44:12.282 [                     main] [WARN ] [            c.h.s.d.integration.DiscoveryService] : [10.1.32.52]:5701 [dev] [3.12] Cannot fetch the current zone, ZONE_AWARE feature is disabled 
2019-05-01 20:44:12.285 [                     main] [DEBUG] [             c.h.internal.cluster.ClusterService] : [10.1.32.52]:5701 [dev] [3.12] Setting master address to null 
2019-05-01 20:44:12.690 [                     main] [TRACE] [         c.hazelcast.kubernetes.KubernetesClient] : Node does not have ExternalIP assigned 
com.hazelcast.kubernetes.KubernetesClientException: Node does not have ExternalIP assigned
	at com.hazelcast.kubernetes.KubernetesClient.extractNodePublicIp(KubernetesClient.java:431)
	at com.hazelcast.kubernetes.KubernetesClient.enrichWithPublicAddresses(KubernetesClient.java:304)
	at com.hazelcast.kubernetes.KubernetesClient.endpointsByName(KubernetesClient.java:111)
	at com.hazelcast.kubernetes.KubernetesApiEndpointResolver.resolve(KubernetesApiEndpointResolver.java:56)
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:97)
```

I don't have an ExternalIP because my service is not using a public Load Balancer.

I'm wondering if this code
```java
private static String extractNodePublicIp(JsonObject nodeJson) {
        for (JsonValue address : toJsonArray(nodeJson.get("status").asObject().get("addresses"))) {
            if ("ExternalIP".equals(address.asObject().get("type").asString())) {
                return address.asObject().get("address").asString();
            }
        }
        throw new KubernetesClientException("Node does not have ExternalIP assigned");
    }
```
should use `InternalIP` in my case? Would that work?

**Comment by hasancelik** [comment]
@hugree , as @leszko mentioned above, if your kubernetes clusters are in the same network(VPC), you don't need to expose IPs with Metacontroller. You can connect to master cluster from other clusters via just configuring `kubernetes-master`, `api-token` and `ca-certificate`:
```
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <network>
            <join>
                <multicast enabled="false"/>
                <kubernetes enabled="true">
                    <kubernetes-master>/kubernetes-master>
                    <api-token></api-token>
                    <ca-certificate>
                        -----BEGIN CERTIFICATE----- 
                        -----END CERTIFICATE-----
                    </ca-certificate>
                </kubernetes>
            </join>
        </network>
    </hazelcast>
```
master cluster config:
```
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <network>
          <join>
            <kubernetes enabled="true" />
            <multicast enabled="false" />
          </join>
        </network>
    </hazelcast>
```

**Comment by hugree** [comment]
> @hugree , as @leszko mentioned above, if your kubernetes clusters are in the same network(VPC), you don't need to expose IPs with Metacontroller. You can connect to master cluster from other clusters via just configuring `kubernetes-master`, `api-token` and `ca-certificate`:

Thanks for the input but that's how my clusters have been configured already.

I'm deep in debugging the `KubernetesClient.java` source code and since the `enrichWithPublicAddresses` method is always called I don't see how I can "steer" the code to now look for the public addresses hence the `Node does not have ExternalIP assigned` errors is as far as I got without creating the public Load Balancer for the service, which I don't actually need.

It would be great it @leszko confirmed or denied my suspicion that this case is not handled in the current version of this library???


Btw... I did try to use the Load Balancer... just for testing and this is what I ended up with
```
2019-05-01 21:38:46.191 [hz.default-cluster.priority-generic-operation.thread-0] [DEBUG] [             c.h.internal.cluster.ClusterService] : [10.1.32.88]:5701 [dev] [3.12] Not finalizing join because caller: [13.80.138.127]:5701 is not known master: [10.1.16.31]:5701 
2019-05-01 21:38:46.191 [hz.default-cluster.priority-generic-operation.thread-0] [DEBUG] [             c.h.internal.cluster.ClusterService] : [10.1.32.88]:5701 [dev] [3.12] Cannot send explicit suspicion, not joined yet! 
2019-05-01 21:38:46.191 [hz.default-cluster.priority-generic-operation.thread-0] [DEBUG] [           c.h.i.cluster.impl.ClusterJoinManager] : [10.1.32.88]:5701 [dev] [3.12] Handling master response [10.1.16.31]:5701 from [13.80.138.127]:5701 
2019-05-01 21:38:46.191 [hz.default-cluster.priority-generic-operation.thread-0] [DEBUG] [             c.h.internal.cluster.ClusterService] : [10.1.32.88]:5701 [dev] [3.12] Setting master address to [10.1.16.31]:5701 
2019-05-01 21:38:46.191 [hz.default-cluster.priority-generic-operation.thread-0] [WARN ] [           c.h.i.cluster.impl.ClusterJoinManager] : [10.1.32.88]:5701 [dev] [3.12] Could not create connection to possible master [10.1.16.31]:5701 
```
From the looks of it the public address of the load balancer got mixed with private addresses and the cluster, in the end, was not able to form correctly.

**Comment by hugree** [comment]
@leszko I went with my gut and modified the `extractNodePublicIp` method to use `InternalIP` instead of `ExternalIP` in my case as I was hinting above. I was finally able to form a multi k8s hazelcast cluster :D.  

I would like to prepare a PR so please let me know if my findings are correct or not.

**Comment by hasancelik** [comment]
@hugree The external smart client implementation is `ExternalIP` centric and it is a design decision. I am not sure about we should support this kind of setup because we have already solution for them as mentioned above. 

btw, @leszko will not be online until the end of the next week. He can answer your questions when he is online.

**Comment by googlielmo** [comment]
Hi @hugree I was reading this thread but I'm not sure I follow. Cannot you share the server and client configuration?

**Comment by leszko** [comment]
@hugree ok, I'm back, let me comment on this. 

I think I missed the point from the beginning. If I understand it correctly, you'd like to create one Hazelcast cluster across two different Kubernetes clusters within one VPC. So, for example, you'll have k8 **cluster1** and k8 **cluster2** and in each cluster you'll have 3 Hazelcast members:
- **cluster1: hz1, hz2, hz3**
- **cluster2: hz4, hz5, hz6**
And you'd like them all to form one Hazelcast cluster having 6 members. Do I understand correctly?

A few comments on that:

1. Your k8 **cluster1** and **cluster2** should be in the same region, otherwise you would have a Hazelcast cluster across different geographical regions, which would kill the performance.

2. The standard solution for your problem would be to have one k8 cluster across different availability zones. And then using Hazelcast ZONE_AWARE feature.

3. If that does not solve your issue, then you would kind-of need multiple discovery strategy for Hazelcast. Meaning that one discovery strategy would discover members in the same k8 cluster and the other discovery strategy would discover in the other cluster. For example, for **hz1**
 - Strategy 1: discovery in **cluster1**: **hz2**, **hz3**
 - Strategy 2: discovery in **cluster2**: **hz4**, **hz5**, **hz6**

However, Hazelcast does not support multiple discovery strategies. You can raise an issue in [hazelcast/hazelcast](https://github.com/hazelcast/hazelcast).

4. A workaround, which I actually do not recommend, is to use the standard discovery in **cluster1** members.

```
      <kubernetes enabled="true"/>
```

And the "external" configuration for **cluster2**.

```
      <kubernetes enabled="true">
          <namespace>NAMESPACE</namespace>
          <kubernetes-master>CLUSTER1_KUBERNETES_MASTER</kuberntes-master>
          <api-token>CLUSTER1_API_TOKEN</api-token>
          <ca-certificate>CLUSTER1_CA_CERTIFICATE</ca-certificate>
      </kubernetes>
```

You don't need any Metacontrollers, etc, because you're in the same VPC. This should work, however, the problem with such configuration, and the reason why I don't recommend it, is that if your **cluster1** whole fails, then the members in **cluster2** won't be able to discover themselves.

**Comment by leszko** [comment]
@hugree Also keep in mind that with such custom cases, you can always use a service registry like Eureka, then you can configure whatever you want.

**Comment by leszko** [comment]
Closing due to inactivity. Feel free to reopen if needed.

**Comment by AayushiKhandelwal123** [comment]
Hi @hugree  please tell whether one of the solutions mentioned by @leszko worked for you.  @leszko  please suggest something for the aks clusters in  different VPC. Thanks.

**Comment by AayushiKhandelwal123** [comment]
> @hugree ok, I'm back, let me comment on this.
> 
> I think I missed the point from the beginning. If I understand it correctly, you'd like to create one Hazelcast cluster across two different Kubernetes clusters within one VPC. So, for example, you'll have k8 **cluster1** and k8 **cluster2** and in each cluster you'll have 3 Hazelcast members:
> 
> * **cluster1: hz1, hz2, hz3**
> * **cluster2: hz4, hz5, hz6**
>   And you'd like them all to form one Hazelcast cluster having 6 members. Do I understand correctly?
> 
> A few comments on that:
> 
> 1. Your k8 **cluster1** and **cluster2** should be in the same region, otherwise you would have a Hazelcast cluster across different geographical regions, which would kill the performance.
> 2. The standard solution for your problem would be to have one k8 cluster across different availability zones. And then using Hazelcast ZONE_AWARE feature.
> 3. If that does not solve your issue, then you would kind-of need multiple discovery strategy for Hazelcast. Meaning that one discovery strategy would discover members in the same k8 cluster and the other discovery strategy would discover in the other cluster. For example, for **hz1**
> 
> * Strategy 1: discovery in **cluster1**: **hz2**, **hz3**
> * Strategy 2: discovery in **cluster2**: **hz4**, **hz5**, **hz6**
> 
> However, Hazelcast does not support multiple discovery strategies. You can raise an issue in [hazelcast/hazelcast](https://github.com/hazelcast/hazelcast).
> 
> 1. A workaround, which I actually do not recommend, is to use the standard discovery in **cluster1** members.
> 
> ```
>       <kubernetes enabled="true"/>
> ```
> 
> And the "external" configuration for **cluster2**.
> 
> ```
>       <kubernetes enabled="true">
>           <namespace>NAMESPACE</namespace>
>           <kubernetes-master>CLUSTER1_KUBERNETES_MASTER</kuberntes-master>
>           <api-token>CLUSTER1_API_TOKEN</api-token>
>           <ca-certificate>CLUSTER1_CA_CERTIFICATE</ca-certificate>
>       </kubernetes>
> ```
> 
> You don't need any Metacontrollers, etc, because you're in the same VPC. This should work, however, the problem with such configuration, and the reason why I don't recommend it, is that if your **cluster1** whole fails, then the members in **cluster2** won't be able to discover themselves.

Hi @hugree please tell whether one of the solutions mentioned by @leszko worked for you. @leszko please suggest something for the aks clusters in different VPC. Thanks.

**Comment by paritalagt** [comment]
I am also struggling to connect two hazelcast pod running on two different k8 cluster together so they can communicate with each other

**Comment by paritalagt** [comment]
I am using hazelcast for braodcasting message but issue is i have total 4 pods running in two different cluster if one pod broadcast hazelcast messages it should broadcast to all the pods

**Comment by rashi13** [comment]
hi @paritalagt  
did the solution work?

**Comment by rashi13** [comment]
> @hugree ok, I'm back, let me comment on this.
> 
> I think I missed the point from the beginning. If I understand it correctly, you'd like to create one Hazelcast cluster across two different Kubernetes clusters within one VPC. So, for example, you'll have k8 **cluster1** and k8 **cluster2** and in each cluster you'll have 3 Hazelcast members:
> 
> * **cluster1: hz1, hz2, hz3**
> * **cluster2: hz4, hz5, hz6**
>   And you'd like them all to form one Hazelcast cluster having 6 members. Do I understand correctly?
> 
> A few comments on that:
> 
> 1. Your k8 **cluster1** and **cluster2** should be in the same region, otherwise you would have a Hazelcast cluster across different geographical regions, which would kill the performance.
> 2. The standard solution for your problem would be to have one k8 cluster across different availability zones. And then using Hazelcast ZONE_AWARE feature.
> 3. If that does not solve your issue, then you would kind-of need multiple discovery strategy for Hazelcast. Meaning that one discovery strategy would discover members in the same k8 cluster and the other discovery strategy would discover in the other cluster. For example, for **hz1**
> 
> * Strategy 1: discovery in **cluster1**: **hz2**, **hz3**
> * Strategy 2: discovery in **cluster2**: **hz4**, **hz5**, **hz6**
> 
> However, Hazelcast does not support multiple discovery strategies. You can raise an issue in [hazelcast/hazelcast](https://github.com/hazelcast/hazelcast).
> 
> 1. A workaround, which I actually do not recommend, is to use the standard discovery in **cluster1** members.
> 
> ```
>       <kubernetes enabled="true"/>
> ```
> 
> And the "external" configuration for **cluster2**.
> 
> ```
>       <kubernetes enabled="true">
>           <namespace>NAMESPACE</namespace>
>           <kubernetes-master>CLUSTER1_KUBERNETES_MASTER</kuberntes-master>
>           <api-token>CLUSTER1_API_TOKEN</api-token>
>           <ca-certificate>CLUSTER1_CA_CERTIFICATE</ca-certificate>
>       </kubernetes>
> ```
> 
> You don't need any Metacontrollers, etc, because you're in the same VPC. This should work, however, the problem with such configuration, and the reason why I don't recommend it, is that if your **cluster1** whole fails, then the members in **cluster2** won't be able to discover themselves.

@leszko 

The solution  provided here has different configurations set up in deployment.yaml
In my case the deployment.yaml file will be the same
