### ISSUE TITLE
Failure to trust OpenShift Master API certificates

### ISSUE THREAD

**Issue by sanssucre** [hazelcast/hazelcast-kubernetes#174]
In CodeReady Containers AKA OpenShift 4.1 (single node dev instance) there seems to be a problem with the certificate chain.  A similar issue related to elastic can be found here: https://access.redhat.com/solutions/3921041.  
The kubernetes api call fails on startup with the following stack trace:
com.hazelcast.kubernetes.RestClientException: Failure in executing REST call
	at com.hazelcast.kubernetes.RestClient.call(RestClient.java:113) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.RestClient.get(RestClient.java:78) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.KubernetesClient$1.call(KubernetesClient.java:475) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.KubernetesClient$1.call(KubernetesClient.java:469) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.RetryUtils.retry(RetryUtils.java:53) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.KubernetesClient.callGet(KubernetesClient.java:469) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.KubernetesClient.endpoints(KubernetesClient.java:80) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.KubernetesApiEndpointResolver.resolve(KubernetesApiEndpointResolver.java:60) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:97) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:71) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:70) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddressesForInitialJoin(DiscoveryJoiner.java:59) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:138) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:98) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:137) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.instance.Node.join(Node.java:809) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.instance.Node.start(Node.java:444) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:136) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57) ~[hazelcast-3.12.2.jar!/:3.12.2]
	at com.bncf.mcp.rate_limiting_service.Assembly.<init>(Assembly.java:38) ~[classes!/:0.0.21]
	at com.bncf.mcp.rate_limiting_service.Assembly$$EnhancerBySpringCGLIB$$b88297f0.<init>(<generated>) ~[classes!/:0.0.21]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1295) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1197) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845) ~[spring-beans-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:743) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:390) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203) ~[spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
	at com.bncf.mcp.rate_limiting_service.RateLimitingServiceApplication.main(RateLimitingServiceApplication.java:14) ~[classes!/:0.0.21]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[rate_limiting_service-0.0.21.jar:0.0.21]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[rate_limiting_service-0.0.21.jar:0.0.21]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[rate_limiting_service-0.0.21.jar:0.0.21]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[rate_limiting_service-0.0.21.jar:0.0.21]
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:641) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:460) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360) ~[na:na]
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177) ~[na:na]
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[na:na]
	at com.hazelcast.kubernetes.RestClient.checkHttpOk(RestClient.java:130) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	at com.hazelcast.kubernetes.RestClient.call(RestClient.java:110) ~[hazelcast-kubernetes-1.5.1.jar!/:na]
	... 55 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:290) ~[na:na]
	at java.base/sun.security.validator.Validator.validate(Validator.java:264) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:625) ~[na:na]
	... 73 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[na:na]
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126) ~[na:na]
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380) ~[na:na]
	... 79 common frames omitted

Let me know if i can help!

**Comment by leszko** [comment]
Is the issue related to Hazelcast? From the link you sent it seems the resolution is on the OpenShift side.

```
oc set env dc/logging-es-xxxx KUBERNETES_TRUST_CERTIFICATES=true
```

**Comment by sanssucre** [comment]
If i understand it well, the environment variable works because elastic uses a Kubernetes client lib (https://github.com/kubernetes-client/java?) that behaves differently when this environment variable is present.  It makes sense that it's something that happens on the client side since it's the client that refuses to accept the certificate.

**Comment by mesutcelik** [comment]
`KUBERNETES_TRUST_CERTIFICATES` is a feature provided by [Fabric8 Kubernetes Client](https://github.com/fabric8io/kubernetes-client)

[Hazelcast RestClient](https://github.com/hazelcast/hazelcast-kubernetes/blob/master/src/main/java/com/hazelcast/kubernetes/RestClient.java) does not have such a feature to enable [HostnameVerifier](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/HostnameVerifier.html) which trusts everything but it can be implemented easily by adding such code snippet to RestClient and enable it via an env. variable or System Property

**please note that this is something you should not enable in prod environments.**

```
HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
        public boolean verify(String hostname, SSLSession session) {
            return true;
        }
    });
```

**Comment by sanssucre** [comment]
Thanks for that.  I understand that you might not want to add this to the code base but since it's easy enough to do outside i guess it's no big deal.  And agreed not in prod :)
