### ISSUE TITLE
Cannot fetch services dedicated to the following PODs

### ISSUE THREAD

**Issue by ChangSurrey** [hazelcast/hazelcast-kubernetes#177]
I'm using v1.5.2 of the plugin and hazelcast v3.12.3. 

I have 2 pods (same namespace) that are created through a StatefulSet, and they're configured to use the following to discover hazelcast member: 

```
<network>
            <join>
                <multicast enabled="false" />
                <tcp-ip enabled="false" />
                <kubernetes enabled="true">
                    <namespace>test-namespace</namespace>
                    <service-name>internal</service-name>
                </kubernetes>
            </join>
            <interfaces enabled="true">
                <interface>172.*.*.*</interface> <!-- Docker network interface -->
            </interfaces>
        </network>
```

Output of `kubectl -n test-namespace get endpoints`
```
NAME                 ENDPOINTS                               AGE
backend    172.40.11.145:8090,172.40.21.197:8090   15m
frontend   172.40.11.145:8080,172.40.21.197:8080   15m
internal   172.40.11.145:5701,172.40.21.197:5701   15m
ingress-nginx        172.40.21.236:80,172.40.21.236:80       15m
```

Output of `kubectl -n test-namespace get pods -o wide`
```
NAME                                        READY   STATUS    RESTARTS   AGE   IP              NODE                                          NOMINATED NODE   READINESS GATES
primary-0                         1/1     Running   0          48m   172.40.11.73    ip-172-40-11-32.eu-west-1.compute.internal    <none>           <none>
primary-1                         1/1     Running   0          48m   172.40.21.197   ip-172-40-21-146.eu-west-1.compute.internal   <none>           <none>
nginx-ingress-controller-68c787c99c-ntll9   1/1     Running   0          48m   172.40.21.223   ip-172-40-21-146.eu-west-1.compute.internal   <none>           <none>
```

Output of `kubectl -n test-namespace get svc`
```
NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP                                                              PORT(S)                      AGE
backend    ClusterIP      10.100.98.249    <none>                                                                   8090/TCP                     48m
frontend   ClusterIP      10.100.8.155     <none>                                                                   8080/TCP                     48m
internal   ClusterIP      10.100.219.247   <none>                                                                   5701/TCP                     48m
ingress-nginx        LoadBalancer   10.100.66.166    ***.eu-west-1.elb.amazonaws.com   80:30534/TCP,443:30209/TCP   48m
```

Service definition: 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    endpoint: cluster
  name: internal
  namespace: test-namespace
spec:
  ports:
  - name: hazelcast
    port: 5701
    protocol: TCP
```

When I use 2 pods in the same namespace to join a cluster, I get the following exception: 

```
com.hazelcast.kubernetes.KubernetesClientException: Cannot fetch services dedicated to the following PODs: [172.40.11.73:5701, 172.40.21.197:5701]
	at com.hazelcast.kubernetes.KubernetesClient.extractServices(KubernetesClient.java:375) ~[hazelcast-kubernetes-1.5.2.jar:?]
	at com.hazelcast.kubernetes.KubernetesClient.enrichWithPublicAddresses(KubernetesClient.java:302) ~[hazelcast-kubernetes-1.5.2.jar:?]
	at com.hazelcast.kubernetes.KubernetesClient.endpointsByName(KubernetesClient.java:115) ~[hazelcast-kubernetes-1.5.2.jar:?]
	at com.hazelcast.kubernetes.KubernetesApiEndpointResolver.resolve(KubernetesApiEndpointResolver.java:62) ~[hazelcast-kubernetes-1.5.2.jar:?]
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:108) ~[hazelcast-kubernetes-1.5.2.jar:?]
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:71) ~[hazelcast-3.12.3.jar:3.12.3]
	at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:70) ~[hazelcast-3.12.3.jar:3.12.3]
	at com.hazelcast.cluster.impl.TcpIpJoiner.searchForOtherClusters(TcpIpJoiner.java:426) ~[hazelcast-3.12.3.jar:3.12.3]
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.searchForOtherClusters(SplitBrainHandler.java:75) ~[hazelcast-3.12.3.jar:3.12.3]
	at com.hazelcast.internal.cluster.impl.SplitBrainHandler.run(SplitBrainHandler.java:42) ~[hazelcast-3.12.3.jar:3.12.3]
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77) ~[hazelcast-3.12.3.jar:3.12.3]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227) ~[hazelcast-3.12.3.jar:3.12.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-3.12.3.jar:3.12.3]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-3.12.3.jar:3.12.3]
```

In `kubernetes/KubernetesClient.java`'s `extractServices()` I can see the following code: 
```
for (JsonValue item : toJsonArray(endpointsListJson.get("items"))) {
            String service = toString(item.asObject().get("metadata").asObject().get("name"));
            List<Endpoint> endpoints = parseEndpoints(item);
            // Service must point to exactly one endpoint address, otherwise the public IP would be ambiguous.
            if (endpoints.size() == 1) {
                EndpointAddress address = endpoints.get(0).getPrivateAddress();
                if (left.contains(address)) {
                    result.put(address, service);
                    left.remove(address);
                }
            }
        }
        if (!left.isEmpty()) {
            // At least one Hazelcast Member POD does not have a corresponding service.
            throw new KubernetesClientException(String.format("Cannot fetch services dedicated to the following PODs: %s", left));
        }
```

Why does each service must point to exactly one endpoint address? Is that what's causing the issue?

**Comment by leszko** [comment]
Do you try to configure Hazelcast [to use with the external client](https://github.com/hazelcast/hazelcast-kubernetes#outside-kubernetes-cluster)?

If yes, then one service must point to one POD, otherwise it's not properly exposed outside Kubernetes cluster.

If not, then this log is on the debug level and should not prevent your Hazelcast from working correctly. You can ignore it. It just means that the Hazelcast members are not exposed outside Kubernetes cluster and you can't therefore use it from outside.

**Comment by ChangSurrey** [comment]
@leszko not really - all my pods are within an internal subnet which can only be reached through an ELB that points at the service. 

Thanks for the explanation - yes I believe I can ignore them now.
