### ISSUE TITLE
Kubernetes Discovery is not working in Quarkus

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-kubernetes#181]
This guide works fine with Docker Images generated from Quarkus Jar file.
https://github.com/hazelcast-guides/hazelcast-quarkus-kubernetes

However, if you build Docker image from Native Image then you get an Exception.

**How to create Docker Image**
```
mvn package -Pnative -Dnative-image.docker-build=true
docker build -f Dockerfile.native -t hazelcast-quarkus-kubernetes-native .
```

If you use `hazelcast-quarkus-kubernetes-native` in [here](https://github.com/hazelcast-guides/hazelcast-quarkus-kubernetes/blob/master/hazelcast-quarkus-client.yaml) then you get following exception.

```
Caused by: com.hazelcast.config.InvalidConfigurationException: Invalid configuration
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:147)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:57)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
	at com.hazelcast.client.impl.clientside.ClientDiscoveryServiceBuilder.initDiscoveryService(ClientDiscoveryServiceBuilder.java:268)
	at com.hazelcast.client.impl.clientside.ClientDiscoveryServiceBuilder.build(ClientDiscoveryServiceBuilder.java:92)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.initClientDiscoveryService(HazelcastClientInstanceImpl.java:300)
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:243)
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:195)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:132)
	at guides.hazelcast.spring.HazelcastClientConfig.createInstance(HazelcastClientConfig.java:19)
	at guides.hazelcast.spring.HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.create(HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.zig:42)
	at guides.hazelcast.spring.HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.get(HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.zig:69)
	at guides.hazelcast.spring.HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.get(HazelcastClientConfig_ProducerMethod_createInstance_ed75ad1c313ec6072a30b51e9e2ab3505c6de911_Bean.zig:148)
	at guides.hazelcast.spring.CommandController_Bean.create(CommandController_Bean.zig:46)
	at guides.hazelcast.spring.CommandController_Bean.create(CommandController_Bean.zig:312)
	at io.quarkus.arc.RequestContext.get(RequestContext.java:66)
	at guides.hazelcast.spring.CommandController_ClientProxy.arc$delegate(CommandController_ClientProxy.zig:220)
	at guides.hazelcast.spring.CommandController_ClientProxy.arc_contextualInstance(CommandController_ClientProxy.zig:39)
	at io.quarkus.arc.runtime.ClientProxyUnwrapper.apply(ClientProxyUnwrapper.java:11)
	at io.quarkus.resteasy.server.common.runtime.ResteasyServerCommonRecorder$1.apply(ResteasyServerCommonRecorder.java:19)
	at io.quarkus.resteasy.server.common.runtime.QuarkusInjectorFactory$UnwrappingPropertyInjector.inject(QuarkusInjectorFactory.java:71)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.lambda$createResource$1(POJOResourceFactory.java:70)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:70)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:352)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	... 51 more
Caused by: com.hazelcast.config.properties.ValidationException: There is no discovery strategy factory to create 'DiscoveryStrategyConfig{properties={service-name=hazelcast-cluster}, className='com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy', discoveryStrategyFactory=null}' Is it a typo in a strategy classname? Perhaps you forgot to include implementation on a classpath?
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:186)
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:141)
	... 78 more
```

**Comment by mesutcelik** [comment]
I am going to try to setup [reflection-config.json](https://github.com/hazelcast-guides/hazelcast-quarkus-kubernetes/blob/master/src/main/resources/reflection-config.json) but hit some quarkus problem. 
related issue https://github.com/quarkusio/quarkus/issues/6123

**Comment by pivovarit** [comment]
The discovery strategy relies on the Java SPI which requires some extra care beyond just registering it for reflection

I solved it in the extension using Quarkus-provided tools: https://github.com/pivovarit/quarkus-hazelcast-client-extension/pull/97

**Comment by pivovarit** [comment]
This is how Quarkus does it internally: https://github.com/quarkusio/quarkus/blob/8e20d02f9059fae2325aa218d49f0fb8a16af64b/core/deployment/src/main/java/io/quarkus/deployment/steps/NativeImageAutoFeatureStep.java#L195-L228

**Comment by pivovarit** [comment]
Kubernetes API is accessible only using HTTPS which means, SSL support needs to be enabled and properly configured (`java.library.path` and `javax.net.ssl.trustStore` parameters)

For example:
```
 FROM quay.io/quarkus/ubi-quarkus-native-image:19.2.1 as graalvm
  FROM registry.access.redhat.com/ubi8/ubi-minimal
  WORKDIR /work/
  COPY --from=graalvm /opt/graalvm/jre/lib/security/cacerts /work/cacerts
  COPY --from=graalvm /opt/graalvm/jre/lib/amd64/libsunec.so /work/lib/libsunec.so

  COPY target/*-runner /work/application
  RUN chmod 775 /work
  EXPOSE 8080
  CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
  CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djava.library.path=/work/lib", "-Djavax.net.ssl.trustStore=/work/cacerts"]
 ```

**Comment by pivovarit** [comment]
Besides the reason mentioned above, GraalVM requires some extra configuration for proper HTTPS support - the support is already provided in [our extension](http://github.com/hazelcast/quarkus-hazelcast-client/)
