### ISSUE TITLE
NoSuchMethodError: io.fabric8.kubernetes.client.ConfigBuilder.build()Lio/fabric8/kubernetes/client/Config;

### ISSUE THREAD

**Issue by RobinsChens** [hazelcast/hazelcast-kubernetes#20]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.fabric8.kubernetes.client.Config]: Factory method 'kubernetesClientConfig' threw exception; nested exception is java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.ConfigBuilder.build()Lio/fabric8/kubernetes/client/Config;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 23 common frames omitted
Caused by: java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.ConfigBuilder.build()Lio/fabric8/kubernetes/client/Config;

**Comment by noctarius** [comment]
Can you please add some more information? What version of the plugin, what Hazelcast version, what Spring version and let me guess you use Spring Boot?

**Comment by noctarius** [comment]
*ping*

**Comment by artak116** [comment]
Hi,

We have a same mentioned issue.

Our versions are:
Hazelcast - 3.8.3
Hazelcast-Kubernetes - 1.0.0
Spring Boot - 1.5.2
kubernetes - 1.5.1

Issue appears when hazelcast client tries to connect hazelcast  servers.

**Comment by lazerion** [comment]
Issue resolved on @artak116 side. 
@RobinsChens do you need support?

**Comment by lazerion** [comment]
Closing due to inactivity, please feel free to open.
