### ISSUE TITLE
Cannot set Hazelcast port with pod-label discovery

### ISSUE THREAD

**Issue by pxsalehi** [hazelcast/hazelcast-kubernetes#208]
I'm using pod-label-name/value to define HC pods that should form a cluster, as follows:
```
<kubernetes enabled="false">
	<pod-label-name>orientdb-cluster-member</pod-label-name>
	<pod-label-value>true</pod-label-value>
</kubernetes>
```

However, since I am not using the default HC port (5701), I am not able to override the port that the endpoint discovery uses to connect to other HC instance. If I define a `service-port` in the above config, I get error regarding validity of the config file:
```
2020-06-10 12:05:55:104 WARNI Name of the hazelcast schema location is incorrect, using default [AbstractXmlConfigHelper][node1591790754586] Error on starting distributed plugin
com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'kubernetes'. One of '{"http://www.hazelcast.com/schema/config":tcp-ip, "http://www.hazelcast.com/schema/config":aws, "http://www.hazelcast.com/schema/config":discovery-strategies}' is expected.
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:189)
	at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:242)
	at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:223)
	at com.hazelcast.config.FileSystemXmlConfig.<init>(FileSystemXmlConfig.java:95)
	at com.hazelcast.config.FileSystemXmlConfig.<init>(FileSystemXmlConfig.java:61)
	at com.hazelcast.config.FileSystemXmlConfig.<init>(FileSystemXmlConfig.java:47)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.configureHazelcast(OHazelcastPlugin.java:728)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:154)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1178)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:465)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:48)
Caused by: org.xml.sax.SAXParseException; lineNumber: 35; columnNumber: 32; cvc-complex-type.2.4.a: Invalid content was found starting with element 'kubernetes'. One of '{"http://www.hazelcast.com/schema/config":tcp-ip, "http://www.hazelcast.com/schema/config":aws, "http://www.hazelcast.com/schema/config":discovery-strategies}' is expected.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:453)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3231)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1791)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:741)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:568)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.validate(ValidatorHandlerImpl.java:726)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:102)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:187)
	... 10 more
```

I've tried using a service for discovery and since I am able to override the port, it works. I have also tried using the default port in my code, when using pod-label discovery, and it also works! So I think the problem is not being able to override the port when not using service-based discovery. I am using v1.5.3.

**Comment by leszko** [comment]
I just tried, but could not reproduce it with the latest Hazelcast version. Could you please check the latest Hazelcast (it should actually be the same as `1.5.3`) and write here the steps to reproduce?

I tried the following Hazelcast configuration:
```
hazelcast:
  yaml:
    hazelcast:
      network:
        port:
          port: 5702
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            pod-label-name: app.kubernetes.io/instance
            pod-label-value: my-release
            service-port: 5702
```

Here's the log, which looks correct.
```
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: null, service-port: 5702, service-label: null, service-label-value: true, namespace: default, pod-label: app.kubernetes.io/instance, pod-label-value: my-release, resolve-not-ready-addresses: true, use-node-name-as-external-address: false, kubernetes-api-retries: 3, kubernetes-master: https://kubernetes.default.svc}
Jun 15, 2020 9:17:55 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Kubernetes Discovery activated with mode: KUBERNETES_API
Jun 15, 2020 9:17:55 AM com.hazelcast.instance.impl.Node
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Activating Discovery SPI Joiner
Jun 15, 2020 9:17:55 AM com.hazelcast.cp.CPSubsystem
WARNING: [10.24.1.7]:5702 [dev] [4.0.1] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
Jun 15, 2020 9:17:56 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks)
Jun 15, 2020 9:17:56 AM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Jun 15, 2020 9:17:56 AM com.hazelcast.core.LifecycleService
INFO: [10.24.1.7]:5702 [dev] [4.0.1] [10.24.1.7]:5702 is STARTING
Jun 15, 2020 9:17:57 AM com.hazelcast.spi.discovery.integration.DiscoveryService
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Kubernetes plugin discovered availability zone: us-central1-c
Jun 15, 2020 9:17:57 AM com.hazelcast.kubernetes.KubernetesClient
WARNING: Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
Jun 15, 2020 9:18:02 AM com.hazelcast.internal.cluster.ClusterService
INFO: [10.24.1.7]:5702 [dev] [4.0.1]

Members {size:1, ver:1} [
        Member [10.24.1.7]:5702 - 9b8efdc5-5647-436b-9888-3957b64e547d this
]

Jun 15, 2020 9:18:02 AM com.hazelcast.core.LifecycleService
INFO: [10.24.1.7]:5702 [dev] [4.0.1] [10.24.1.7]:5702 is STARTED
Jun 15, 2020 9:18:02 AM com.hazelcast.internal.diagnostics.HealthMonitor
INFO: [10.24.1.7]:5702 [dev] [4.0.1] processors=1, physical.memory.total=3.6G, physical.memory.free=1.2G, swap.space.total=0, swap.space.free=0, heap.memory.used=35.8M, heap.memory.free=66.7M, heap.memory.total=102.5M, heap.memory.max=2.6G, heap.memory.used/total=34.84%, heap.memory.used/max=1.36%, minor.gc.count=6, minor.gc.time=55ms, major.gc.count=1, major.gc.time=42ms, load.process=25.00%, load.system=100.00%, load.systemAverage=1.39, thread.count=36, thread.peakCount=37, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
Jun 15, 2020 9:18:32 AM com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Received auth from Connection[id=3, /10.24.1.7:5702->/10.24.1.8:53725, qualifier=null, endpoint=[10.24.1.8]:53725, alive=true, connectionType=MCJVM], successfully authenticated, clientUuid: 81cd681f-ae0d-4068-8520-94972b3cabf5, client version: 4.0.1
Jun 15, 2020 9:18:33 AM com.hazelcast.client.impl.ClientEngine
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Applying a new client selector :ClientSelector{any}
Jun 15, 2020 9:18:36 AM com.hazelcast.internal.nio.tcp.TcpIpConnection
INFO: [10.24.1.7]:5702 [dev] [4.0.1] Initialized new cluster connection between /10.24.1.7:5702 and /10.24.2.4:42183
Jun 15, 2020 9:18:43 AM com.hazelcast.internal.cluster.ClusterService
INFO: [10.24.1.7]:5702 [dev] [4.0.1]

Members {size:2, ver:2} [
        Member [10.24.1.7]:5702 - 9b8efdc5-5647-436b-9888-3957b64e547d this
        Member [10.24.2.4]:5702 - 2d0a5e89-b770-41e6-b411-e76a91c03624
]
```

**Comment by pxsalehi** [comment]
hmm. Now I can't reproduce it either! Maybe something else was wrong in my XML config. Thanks anyway. :-)
