### ISSUE TITLE
Failed to deploy hazelcast cluster on K8S (Setup on google cloud vms) 

### ISSUE THREAD

**Issue by mansing2** [hazelcast/hazelcast-kubernetes#300]
I have the K8S cluster setup on Google Cloud (not GKE) and trying to setup hazelcast cluster to test external client. 

I have deployed https://github.com/hazelcast-guides/kubernetes-external-client/blob/main/rbac.yaml and https://github.com/hazelcast-guides/kubernetes-external-client/blob/main/hazelcast-cluster.yaml as per the guide https://guides.hazelcast.org/kubernetes-external-client/ but the pods are failing to form a cluster. 

Here are the full logs from the pod. Any help is appreciated. 
```
2021-02-18 07:41:08,027 [ WARN] [main] [c.h.k.RetryUtils]: Couldn't discover Hazelcast members using Kubernetes API, [2] retrying in 2 seconds...
2021-02-18 07:41:15,287 [ WARN] [main] [c.h.k.RetryUtils]: Couldn't discover Hazelcast members using Kubernetes API, [3] retrying in 3 seconds...
2021-02-18 07:41:18,664 [ERROR] [main] [c.h.i.c.i.DiscoveryJoiner]: [192.168.226.69]:5701 [dev] [4.1] Failure in executing REST call
com.hazelcast.kubernetes.RestClientException: Failure in executing REST call
        at com.hazelcast.kubernetes.RestClient.call(RestClient.java:115) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.RestClient.get(RestClient.java:80) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.KubernetesClient$1.call(KubernetesClient.java:496) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.KubernetesClient$1.call(KubernetesClient.java:490) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.RetryUtils.retry(RetryUtils.java:52) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.KubernetesClient.callGet(KubernetesClient.java:490) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.KubernetesClient.endpoints(KubernetesClient.java:81) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.KubernetesApiEndpointResolver.resolve(KubernetesApiEndpointResolver.java:70) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:108) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:72) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:69) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddressesForInitialJoin(DiscoveryJoiner.java:58) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:136) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:96) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:137) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.instance.impl.Node.join(Node.java:808) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.instance.impl.Node.start(Node.java:471) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:123) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91) [hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47) [hazelcast-all-4.1.jar:4.1]
Caused by: java.net.UnknownHostException: kubernetes.default.svc
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
        at java.net.Socket.connect(Socket.java:609) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285) ~[?:?]
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:182) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334) ~[?:?]
        at com.hazelcast.kubernetes.RestClient.checkHttpOk(RestClient.java:132) ~[hazelcast-all-4.1.jar:4.1]
        at com.hazelcast.kubernetes.RestClient.call(RestClient.java:112) ~[hazelcast-all-4.1.jar:4.1]
        ... 22 more
2021-02-18 07:41:18,674 [ERROR] [main] [c.h.i.i.Node]: [192.168.226.69]:5701 [dev] [4.1] Could not join cluster. Shutting down now!
2021-02-18 07:41:18,674 [ INFO] [main] [c.h.c.LifecycleService]: [192.168.226.69]:5701 [dev] [4.1] [192.168.226.69]:5701 is SHUTTING_DOWN
2021-02-18 07:41:18,678 [ WARN] [main] [c.h.i.i.Node]: [192.168.226.69]:5701 [dev] [4.1] Terminating forcefully...
2021-02-18 07:41:18,678 [ INFO] [main] [c.h.i.i.Node]: [192.168.226.69]:5701 [dev] [4.1] Shutting down connection manager...
2021-02-18 07:41:18,684 [ INFO] [main] [c.h.i.i.Node]: [192.168.226.69]:5701 [dev] [4.1] Shutting down node engine...
2021-02-18 07:41:18,704 [ INFO] [main] [c.h.i.i.NodeExtension]: [192.168.226.69]:5701 [dev] [4.1] Destroying node NodeExtension.
2021-02-18 07:41:18,704 [ INFO] [main] [c.h.i.i.Node]: [192.168.226.69]:5701 [dev] [4.1] Hazelcast Shutdown is completed in 26 ms.
2021-02-18 07:41:18,704 [ INFO] [main] [c.h.c.LifecycleService]: [192.168.226.69]:5701 [dev] [4.1] [192.168.226.69]:5701 is SHUTDOWN
2021-02-18 07:41:18,716 [ WARN] [main] [c.h.i.u.PhoneHome]: [192.168.226.69]:5701 [dev] [4.1] Could not schedule phone home task! Most probably Hazelcast failed to start.
2021-02-18 07:41:18,716 [ INFO] [main] [c.h.i.i.Node]: [192.168.226.69]:5701 [dev] [4.1] Node is already shutting down... Waiting for shutdown process to complete...
Exception in thread "main" java.lang.IllegalStateException: Node failed to start!
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:125)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
        at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47)
```

**Comment by SeriyBg** [comment]
@mansing2 did you use any tool to provision your cluster (like kubespary, or something), or is done manually with your own scripts?

**Comment by mansing2** [comment]
@SeriyBg  - Sorry for the delay in response, I set it up by referring to the Kubernetes documentation, used kubeadm. here are the complete steps: https://github.com/mansing2/kubernetes.

**Comment by mansing2** [comment]
Closing this.
