### ISSUE TITLE
Spring boot embedded kubernetes error - Unknown protocol: HTT

### ISSUE THREAD

**Issue by yomal** [hazelcast/hazelcast-kubernetes#307]
In my spring boot app embedded with hazelcast kubernetes I am getting the below error when trying to scale the deployment up or down. If starting only a single pod there is no error but when the pods start to scale up the error repeats for several iterations (increasing the connection id) and then connects with the cluster. This can be observed on the new pod while the existing pod will display 1 or 2 of the same error. Same behavior exists when scaling down. I have used kubernetes API for discovery.

```
2021-04-02 01:16:05 |  INFO [test-service,,,] |  |  |[hz._hzInstance_1_dev.cached.thread-2] c.h.n.t.TcpIpConnector:49 - [10.233.90.81]:5701 [dev] [3.12.5] Connecting to /10.233.96.141:5701, timeout: 10000, bind-any: true
2021-04-02 01:16:05 |  WARN [test-service,,,] |  |  |[hz._hzInstance_1_dev.IO.thread-in-2] c.h.n.t.TcpIpConnection:49 - [10.233.90.81]:5701 [dev] [3.12.5] Connection[id=195, /10.233.90.81:60393->/10.233.96.141:5701, qualifier=null, endpoint=[10.233.96.141]:5701, alive=false, type=NONE] closed. Reason: Exception in Connection[id=195, /10.233.90.81:60393->/10.233.96.141:5701, qualifier=null, endpoint=[10.233.96.141]:5701, alive=true, type=NONE], thread=hz._hzInstance_1_dev.IO.thread-in-2
java.lang.IllegalStateException: Unknown protocol: HTT
        at com.hazelcast.nio.tcp.UnifiedProtocolDecoder.onRead(UnifiedProtocolDecoder.java:107)
        at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:135)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:369)
        at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:354)
        at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:280)
        at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:235)
2021-04-02 01:16:06 |  INFO [test-service,,,] |  |  |[hz._hzInstance_1_dev.cached.thread-2] c.h.n.t.TcpIpConnector:49 - [10.233.90.81]:5701 [dev] [3.12.5] Connecting to /10.233.96.141:5701, timeout: 10000, bind-any: true
2021-04-02 01:16:06 |  INFO [test-service,,,] |  |  |[hz._hzInstance_1_dev.IO.thread-in-0] c.h.n.t.TcpIpConnection:49 - [10.233.90.81]:5701 [dev] [3.12.5] Initialized new cluster connection between /10.233.90.81:34163 and /10.233.96.141:5701
2021-04-02 01:16:13 |  INFO [test-service,,,] |  |  |[hz._hzInstance_1_dev.priority-generic-operation.thread-0] c.h.i.c.ClusterService:49 - [10.233.90.81]:5701 [dev] [3.12.5]

Members {size:2, ver:2} [
        Member [10.233.96.141]:5701 - 5f0fee64-a207-49fa-a581-1e2ecdc834fb
        Member [10.233.90.81]:5701 - d93305d0-1ea9-4207-8806-e29278694704 this
]
```

Spring boot version: 2.2.5.RELEASE
k8s version: v1.18.4
CNI: calico

used below dependencies:
compile group: 'com.hazelcast', name: 'hazelcast', version: '4.0.1'
runtimeOnly group: 'com.hazelcast', name: 'hazelcast-kubernetes', version: '2.2.2'

Same image was deployed in a k8s cluster of v1.20.0(k3d) locally there was no issue in scaling up or down.
Is there any fix for this?

**Comment by yomal** [comment]
Just found out that this issue is seen when linkerd proxy is added. Linkerd creates another container inside the same pod of the service somehow this seems to create an issue. 

Tried by adding another container other than linkerd then the issue cannot be seen. Is there any reason for this?
