### ISSUE TITLE
Unable to connect client using kubernetes discovery strategy from xml

### ISSUE THREAD

**Issue by zarrarrana** [hazelcast/hazelcast-kubernetes#61]
I have a hazelcast 3.9.2  running on kubernetes which is using the HazelcastKubernetesDiscoveryStrategy, no issues. 

When I try to connect a client using the following  xml config. 
```ruby
<hazelcast-client>
  <properties>
    <property name="hazelcast.discovery.enabled">true</property>
  </properties>
  <network>
    <discovery-strategies>
      <discovery-strategy enabled="true"
          class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
          <properties>
            <property name="service-name">something</property>
            <property name="namespace">something</property>
          </properties>
      </discovery-strategy>
    </discovery-strategies>
  </network>
</hazelcast-client>
```

I get the following error. 
```ruby
com.hazelcast.config.InvalidConfigurationException: Invalid configuration
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:151)
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:60)
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
at com.hazelcast.client.impl.HazelcastClientInstanceImpl.initDiscoveryService(HazelcastClientInstanceImpl.java:330)
at com.hazelcast.client.impl.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:239)
at com.hazelcast.client.HazelcastClient$1.createHazelcastInstanceClient(HazelcastClient.java:55)
at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:74)
at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
at CacheConsumer.runApp(CacheConsumer.java:49)
at CacheConsumer.main(CacheConsumer.java:26)
Caused by: com.hazelcast.config.properties.ValidationException: There is no discovery strategy factory to create 'DiscoveryStrategyConfig{properties={namespace=aws-hazelcast, service-name=hazelcast}, className='com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy', discoveryStrategyFactory=null}' Is it a typo in a strategy classname? Perhaps you forgot to include implementation on a classpath?
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:188)
at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:145)
```

But when I try the following code it works fine.
```ruby
DiscoveryConfig dc = config.getNetworkConfig().getDiscoveryConfig();
HazelcastKubernetesDiscoveryStrategyFactory factory = new HazelcastKubernetesDiscoveryStrategyFactory();
DiscoveryStrategyConfig strategyConfig = new DiscoveryStrategyConfig(factory);
strategyConfig.addProperty("service-name","something");
strategyConfig.addProperty("namespace","something");
dc.addDiscoveryStrategyConfig(strategyConfig);
```

There was a similar issue opened but closed: 
https://github.com/hazelcast/hazelcast-kubernetes/issues/59

The issue suggested possible class path issue, it doesn't seem like a class path issue. 
The error message has:
```ruby
 discoveryStrategyFactory=null
```

**Comment by zarrarrana** [comment]
I briefly looked at the code, could it be the null causing this.


DiscoveryStrategyConfig .java
```ruby
public DiscoveryStrategyConfig(String className, Map<String, Comparable> properties) {
        this.className = className;
        this.properties.putAll(properties);
        this.discoveryStrategyFactory = null;
    }
```

DefaultDiscoveryService.java
```ruby
private String getFactoryClassName(DiscoveryStrategyConfig config) {
        if (config.getDiscoveryStrategyFactory() != null) {
            DiscoveryStrategyFactory factory = config.getDiscoveryStrategyFactory();
            return factory.getDiscoveryStrategyType().getName();
        }
        return config.getClassName();
    }
```

**Comment by hasancelik** [comment]
Hi @zarrarrana ,

I tried to start `3.9.2` hazelcast client with your xml. On the first try, I have encountered `com.hazelcast.config.InvalidConfigurationException: Invalid configuration` because I forgot to run `mvn clean install -DskipTests` command after I add `hazelcast-kubernetes` dependency to `pom.xml`:
```
<dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-kubernetes</artifactId>
            <version>1.1.0</version>
</dependency>
```
Then I got another error which is related my local kubernetes setup, not `InvalidConfigurationException`. In the light of this informations, could you try again with `mvn` command?

**Comment by zarrarrana** [comment]
@hasancelik  Thank you for the response. The issue was with the maven-shade-plugin configuration
as suggested in the #59 . 
Adding, ServiceResourceTransformer fixed the issue.
```ruby
<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
```
