### ISSUE TITLE
issues with kubernetes and preparing blog post with a sample

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-kubernetes#69]
see the discussion here: https://gitter.im/hazelcast/hazelcast?at=5ae018a8109bb04332fb0f0d

https://blog.hazelcast.com/deploy-monitor/ could be outdated so we need to update it or just need to write a new one along with a code-samples...

Openshift example can be reused here.
https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/openshift

**Comment by vadimkim** [comment]
I have problems running hazelcast-kubernetes together with management center (this container: https://hub.docker.com/r/hazelcast/management-center/) 
Will add JAVA stacktrace on Monday. It seems man-center can't parse node configuration from the nodes's response.

**Comment by vadimkim** [comment]
```

2018-04-30 08:44:00.436:WARN:oejs.ServletHandler:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.hazelcast.webmonitor.model.DeserializationException: instanceNames field is null
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: 
com.hazelcast.webmonitor.model.DeserializationException: instanceNames field is null
	at com.hazelcast.webmonitor.utils.JsonUtil.safeGet(JsonUtil.java:115)
	at com.hazelcast.webmonitor.utils.JsonUtil.getArray(JsonUtil.java:108)
	at com.hazelcast.webmonitor.model.hz.req.state.TimedMemberState.fromJson(TimedMemberState.java:51)
	at com.hazelcast.webmonitor.controller.CollectorController.process(CollectorController.java:45)
	at com.hazelcast.webmonitor.controller.CollectorController.doCollect(CollectorController.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
2018-04-30 08:44:00.620:WARN:oejs.ServletHandler:/mancenter/collector.do
com.hazelcast.webmonitor.model.DeserializationException: instanceNames field is null
	at com.hazelcast.webmonitor.utils.JsonUtil.safeGet(JsonUtil.java:115)
	at com.hazelcast.webmonitor.utils.JsonUtil.getArray(JsonUtil.java:108)
	at com.hazelcast.webmonitor.model.hz.req.state.TimedMemberState.fromJson(TimedMemberState.java:51)
	at com.hazelcast.webmonitor.controller.CollectorController.process(CollectorController.java:45)
	at com.hazelcast.webmonitor.controller.CollectorController.doCollect(CollectorController.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by vadimkim** [comment]
Hazelcast version: 3.10
Management center version: 3.9.4

**Comment by vadimkim** [comment]
Working behind NAT is not working also.  The same set up I have desribed at Gitter. Fresh logs:
```
2018-04-30 13:02:22.951  INFO 11551 --- [ost-startStop-1] c.h.c.config.XmlClientConfigLocator      : Loading 'hazelcast-client.xml' from classpath.
2018-04-30 13:02:23.037  WARN 11551 --- [ost-startStop-1] c.h.config.AbstractXmlConfigHelper       : Name of the hazelcast schema location is incorrect, using default
2018-04-30 13:02:23.229  INFO 11551 --- [ost-startStop-1] com.hazelcast.core.LifecycleService      : hz.client_0 [dev] [3.10] HazelcastClient 3.10 (20180424 - d9afa99) is STARTING
2018-04-30 13:02:23.679  INFO 11551 --- [ost-startStop-1] c.h.client.spi.ClientInvocationService   : hz.client_0 [dev] [3.10] Running with 2 response threads
2018-04-30 13:02:23.729  INFO 11551 --- [ost-startStop-1] com.hazelcast.core.LifecycleService      : hz.client_0 [dev] [3.10] HazelcastClient 3.10 (20180424 - d9afa99) is STARTED
2018-04-30 13:02:23.770  INFO 11551 --- [ient_0.cluster-] c.h.c.c.ClientConnectionManager          : hz.client_0 [dev] [3.10] Trying to connect to [192.168.99.100]:5701 as owner member
2018-04-30 13:02:23.797  INFO 11551 --- [nt_0.internal-2] c.h.c.c.ClientConnectionManager          : hz.client_0 [dev] [3.10] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/192.168.99.1:46171->/192.168.99.100:5701}, remoteEndpoint=[172.17.0.6]:5701, lastReadTime=2018-04-30 13:02:23.791, lastWriteTime=2018-04-30 13:02:23.786, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.10} as owner with principal ClientPrincipal{uuid='8d9308e0-bc6d-4acf-8769-8fd8215ad2e4', ownerUuid='c7e2d511-bc0b-48ac-a627-9f352d4fe4db'}
2018-04-30 13:02:23.797  INFO 11551 --- [nt_0.internal-2] c.h.c.c.ClientConnectionManager          : hz.client_0 [dev] [3.10] Authenticated with server [172.17.0.6]:5701, server version:3.10 Local address: /192.168.99.1:46171
2018-04-30 13:02:23.814  INFO 11551 --- [lient_0.event-2] c.h.c.spi.impl.ClientMembershipListener  : hz.client_0 [dev] [3.10] 

Members [2] {
	Member [172.17.0.3]:5701 - 90d9f4d6-64f9-4e4f-89d4-348d8b3cbbfb
	Member [172.17.0.6]:5701 - c7e2d511-bc0b-48ac-a627-9f352d4fe4db
}

2018-04-30 13:02:23.815  INFO 11551 --- [ient_0.cluster-] com.hazelcast.core.LifecycleService      : hz.client_0 [dev] [3.10] HazelcastClient 3.10 (20180424 - d9afa99) is CLIENT_CONNECTED
2018-04-30 13:02:23.816  INFO 11551 --- [ost-startStop-1] c.h.internal.diagnostics.Diagnostics     : hz.client_0 [dev] [3.10] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2018-04-30 13:04:26.955 ERROR 11551 --- [ost-startStop-1] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'springSessionRepositoryFilter' defined in class path resource [org/springframework/session/hazelcast/config/annotation/web/http/HazelcastHttpSessionConfiguration.class]: Unsatisfied dependency expressed through method 'springSessionRepositoryFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionRepository': Invocation of init method failed; nested exception is com.hazelcast.core.OperationTimeoutException: Registering listeners is timed out. Last failed member : Member [172.17.0.3]:5701 - 90d9f4d6-64f9-4e4f-89d4-348d8b3cbbfb,  Current time: 2018-04-30 13:04:26.953,  Start time : 2018-04-30 13:02:24.077,  Client invocation timeout : 120000 ms,  Elapsed time : 122876 ms. 
2018-04-30 13:04:26.984  INFO 11551 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
```
Obviously it doesn't understand that cluster is behind NAT and always tries to connect to cluster member IP:port directly.

**Comment by vadimkim** [comment]
Session "split brains" test is now a bit difficult due to this: https://github.com/spring-projects/spring-session/issues/1055
If I have more time I will re-assemle cluster to include this depencency into server

**Comment by vadimkim** [comment]
New test:
Hazelcast version: 3.9.4
Management center version: 3.9.4
Result : I got cluster nodes visible at management center console. Logs are also clean

**Comment by mesutcelik** [comment]
Thanks @vadimkim 
It is good to hear that you have no issues with the current hazelcast-kubernetes integration. please feel free to create an issue if you see a problem or need an enchancement.

I am keeping this issue until we have a blog post and supporting code sample.

**Comment by leszko** [comment]
To avoid confusion, I've created a separate issue for Writing a Blog Post: #90

The Code Samples are already ready: https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/kubernetes
